export const APP_NAME = "FlareDrive";

export const strings = {
  searchPlaceholder: "搜索文件",
  upload: "上传",
  uploadFile: "上传文件",
  uploadImageVideo: "上传图片/视频",
  uploadFolder: "上传文件夹",
  takePhoto: "拍照",
  createFolder: "新建文件夹",
  openTextPad: "记事本",
  noFiles: "这里还没有文件",
  noSearchResult: "没有找到匹配的文件",
  emptyTrash: "回收站是空的",
  emptyShares: "还没有创建分享",
  files: "文件",
  shares: "分享",
  trash: "回收站",
  select: "选择",
  paste: "粘贴",
  allFiles: "全部文件",
  open: "打开",
  download: "下载",
  rename: "重命名",
  move: "移动",
  share: "分享",
  copy: "复制",
  cut: "剪切",
  delete: "删除",
  login: "登录",
  logout: "退出登录",
  transfers: "上传任务",
  webdav: "WebDAV",
  typeAll: "全部",
  typeImage: "图片",
  typeVideo: "视频",
  typeDoc: "文档",
  typeOther: "其他",
};

export default strings;
