export const APP_NAME = "FlareDrive";

export const strings = {
  searchPlaceholder: "搜索文件",
  searchShortcutHint: "按 / 或 Ctrl+K 搜索",
  upload: "上传",
  uploadFile: "上传文件",
  uploadImageVideo: "上传图片/视频",
  uploadFolder: "上传文件夹",
  takePhoto: "拍照",
  createFolder: "新建文件夹",
  openTextPad: "记事本",
  noFiles: "这里还没有文件",
  noFilesHint: "上传文件，或新建一个文件夹",
  noSearchResult: "没有找到文件",
  noSearchResultHint: "换个关键词，或切换搜索范围",
  emptyTrash: "回收站是空的",
  emptyTrashHint: "删除的文件会出现在这里，可随时恢复",
  emptyShares: "还没有分享",
  emptySharesHint: "在文件上点 ⋯ 即可生成链接",
  goToFiles: "去文件页",
  clearSearch: "清空搜索",
  files: "文件",
  shares: "分享",
  trash: "回收站",
  select: "选择",
  paste: "粘贴",
  allFiles: "全部文件",
  open: "打开",
  download: "下载",
  rename: "重命名",
  move: "移动",
  share: "分享",
  copy: "复制",
  cut: "剪切",
  delete: "删除",
  login: "登录",
  logout: "退出登录",
  transfers: "上传任务",
  webdav: "WebDAV",
  typeAll: "全部",
  typeImage: "图片",
  typeVideo: "视频",
  typeDoc: "文档",
  typeOther: "其他",
  showHidden: "显示隐藏文件",
  searchHere: "当前文件夹",
  searchAll: "全盘搜索",
  colName: "名称",
  colSize: "大小",
  colDate: "修改时间",
  folderLabel: "文件夹",
  dropToUpload: "松手上传到当前目录",
  prevFile: "上一个",
  nextFile: "下一个",
  create: "新建",
  newFolderOrNote: "新建文件夹或记事本",
  pastedImage: "粘贴图片",
  copyPath: "复制路径",
  recent: "最近",
  noRecent: "暂无最近打开",
  densityStandard: "标准",
  densityCompact: "紧凑",
  extractCode: "提取码",
  extractCodeOptional: "提取码（可选）",
  extractCodeHint: "留空则无需提取码",
  folderItems: "项",
  copyWebDavGuide: "复制完整说明",
  api: "API",
  apiKeys: "开放接口",
  apiKeysHint: "用密钥通过接口上传文件，完整密钥只显示一次",
  createApiKey: "创建密钥",
  revokeApiKey: "作废",
  apiKeyName: "名称",
  apiKeyExpiry: "有效期",
  apiKeyCustom: "自定义密钥（可选）",
  apiKeyCustomHint: "留空则自动生成高熵密钥",
  apiKeyOnce: "请立即复制，关闭后无法再查看完整密钥",
  copyApiKey: "复制密钥",
  copyUsage: "复制调用说明",
  apiUsage: "调用说明",
  apiNever: "永久",
  apiLastUsed: "最近使用",
  apiNeverUsed: "尚未使用",
  apiNoKeys: "还没有 API 密钥",
  apiExpiry1d: "1 天",
  apiExpiry7d: "7 天",
  apiExpiry30d: "30 天",
  apiExpiryCustom: "自定义小时数",
};

export default strings;
