export const APP_NAME = "FlareDrive";

export const strings = {
  searchPlaceholder: "搜索文件",
  searchShortcutHint: "按 / 或 Ctrl+K 搜索",
  upload: "上传",
  uploadFile: "上传文件",
  uploadImageVideo: "上传图片/视频",
  uploadFolder: "上传文件夹",
  takePhoto: "拍照",
  createFolder: "新建文件夹",
  openTextPad: "记事本",
  noFiles: "这里还没有文件",
  noFilesHint: "上传文件或新建文件夹开始使用",
  noSearchResult: "没有找到匹配的文件",
  noSearchResultHint: "试试其他关键词，或切换搜索范围",
  emptyTrash: "回收站是空的",
  emptyTrashHint: "删除的文件会出现在这里，可随时恢复",
  emptyShares: "还没有创建分享",
  emptySharesHint: "在文件上点「⋯」即可生成分享链接",
  goToFiles: "去文件页",
  clearSearch: "清空搜索",
  files: "文件",
  shares: "分享",
  trash: "回收站",
  select: "选择",
  paste: "粘贴",
  allFiles: "全部文件",
  open: "打开",
  download: "下载",
  rename: "重命名",
  move: "移动",
  share: "分享",
  copy: "复制",
  cut: "剪切",
  delete: "删除",
  login: "登录",
  logout: "退出登录",
  transfers: "上传任务",
  webdav: "WebDAV",
  typeAll: "全部",
  typeImage: "图片",
  typeVideo: "视频",
  typeDoc: "文档",
  typeOther: "其他",
  showHidden: "显示隐藏文件",
  searchHere: "当前文件夹",
  searchAll: "全盘搜索",
  colName: "名称",
  colSize: "大小",
  colDate: "修改时间",
  folderLabel: "文件夹",
  dropToUpload: "松手上传到当前目录",
  prevFile: "上一个",
  nextFile: "下一个",
  create: "新建",
  newFolderOrNote: "新建文件夹或记事本",
  pastedImage: "粘贴图片",
};

export default strings;
